version: '2'
volumes:
  postgres_data: {}
  redis_data: {}
services:
  redis:
    image: redis:3.2.8
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:9.6.2
    environment:
      - POSTGRES_DB=channels_db
      - POSTGRES_USER=channels
      - POSTGRES_PASSWORD=channels
    volumes:
      - postgres_data:/var/lib/postgresql/data
  daphne:
    image: daphne
    build: .
    command: python manage.py runserver 0.0.0.0:80
    environment:
      - DATABASE_URL=psql://channels:channels@postgres:5432/channels_db
    volumes:
      - ".:/code"
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres
